sources:
  - name: strapi
    handler:
      graphql:
        endpoint: https://noise-world-production.up.railway.app/graphql
  - name: github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        # You can provide your SDL or introspection seperately
        source: https://docs.github.com/public/schema.docs.graphql
        operationHeaders:
          Authorization: Bearer {env.GH_ACCESS_TOKEN}
          User-Agent: GraphQL Mesh
    transforms:
      - prefix:
          value: github_
          includeRootOperations: true
serve:
  playground: true