import "ui/styles.css";
import "./../styles/globals.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { ApolloWrapper } from "../providers/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });
const teko = localFont({
  src: [
    {
      path: "../styles/fonts/Teko-Light.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../styles/fonts/Teko-SemiBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../styles/fonts/Teko-Bold.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../styles/fonts/Teko-Medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../styles/fonts/Teko-Regular.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../styles/fonts/Teko-Variable.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-teko",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const delay = Number(
    cookieStore.get("apollo-x-custom-delay" as any)?.value ?? 1000
  );

  return (
    <html lang="en">
      <body className={`${inter.className} ${teko.className}`}>
        <ApolloWrapper delay={delay}>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
