import "ui/styles.css";
import "./../../styles/globals.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { ApolloWrapper } from "../../providers/ApolloWrapper";
import { i18n } from "../../../i18n-config";

const inter = Inter({ subsets: ["latin"] });
const teko = localFont({
  src: [
    {
      path: "../../styles/fonts/Teko-Light.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Teko-SemiBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Teko-Bold.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Teko-Medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Teko-Regular.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Teko-Variable.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-teko",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { dir } from "i18next";

export default async function RootLayout({ children, params }: any) {
  return (
    <html lang={params?.lang} dir={dir(params?.lang)}>
      <body className={`${inter.className} ${teko.className}`}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
