sources:
  - name: strapi
    handler:
      graphql:
        endpoint: https://noise-world-production.up.railway.app/graphql
  - name: github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        # You can provide your SDL or introspection seperately
        source: https://docs.github.com/public/schema.docs.graphql
        operationHeaders:
          Authorization: Bearer {env.GH_ACCESS_TOKEN}
          User-Agent: GraphQL Mesh
    transforms:
      - prefix:
          value: github_
          includeRootOperations: true
  - name: chatGPT
    handler:
      openapi:
        source: ./gpt-oas.yaml
        selectQueryOrMutationField:
          - fieldName: "createChatCompletion" # OAS field name
            type: Mutation # switch method GET from default Mutation into Query
        operationHeaders:
          Authorization: Bearer {env.GPT_ACCESS_TOKEN}
          User-Agent: GraphQL Mesh
    transforms:
      - prefix:
          value: CHAT_GPT_
          includeRootOperations: true

serve:
  playground: true
cache:
  localforage:
    driver: [WEBSQL, INDEXEDDB, LOCALSTORAGE]
plugins:
  - httpDetailsExtensions:
      if: "env.NODE_ENV === 'development'"
